# -*- coding: utf-8 -*-
"""typing_indicator_realtime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwMfv-bGERgZtozQRtTNQfhu60IhtDPD
"""

!pip install streamlit

import streamlit as st

def show_typing_realtime(message="🤖 הבוט מקליד..."):
    """
    מציג אינדיקציית טעינה דינמית בזמן שהבוט מחפש תשובה.
    מחזיר את placeholder שניתן למחוק מאוחר יותר.
    """
    placeholder = st.empty()
    placeholder.markdown(f"<div style='color:gray; font-style:italic;'>{message}</div>", unsafe_allow_html=True)
    return placeholder
